apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wait-me.fullname" . }}-configmap
  labels:
    app: {{ include "wait-me.fullname" . }}
    chart: {{ include "wait-me.chart" . }}
data:
  config.json:
    '{{ .Files.Get "files/config.json"}}' 