global:
  scrape_timeout:      4s
  external_labels:
      monitor: 'codelab-monitor'

scrape_configs:
  - job_name:        'prometheus'
    scrape_interval: 20s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name:        'loki'
    scrape_interval: 20s
    static_configs:
      - targets: ['loki:3100']

  - job_name:        'grafana'
    scrape_interval: 20s
    static_configs:
      - targets: ['grafana:3000']
  
  - job_name:        'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8000']
