apiVersion: apps/v1
kind: Deployment
metadata:
  name: waitme-app-deployment
  labels:
    app: waitme-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: waitme-app
  template:
    metadata:
      labels:
        app: waitme-app
    spec:
      containers:
        - name: waitme-app
          image: rungiantboom/devopslab:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
              
          env:
          - name: DEMO_GREETING
            value: "Hello from the environment"
          - name: DEMO_FAREWELL
            value: "Such a sweet sorrow"
        
      readinessProbe:
        enabled: false
        path: /ready 
        initialDelaySeconds: 30 
        failureThreshold: 60 
        periodSeconds: 10 
        timeoutSeconds: 15

